baseURL               = "https://geekswg.js.cool/"
languageCode          = "zh-CN"
title                 = "毕少侠导航 By WebStack-Hugo 网址导航" #

theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "毕少侠-geekswg"
    description   = "毕少侠 by geekswg Webstack-Hugo 网址导航 | Hugo 主题 BY Bio IT 爱好者"
    upload        = "https://geekswg.js.cool/notepad/"  # 左侧导航栏的"网站提交"
    about         = "https://geekswg.js.cool/"	# 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "毕少侠 ~ 网址导航 Powered By Hugo"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "/imgs/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "/imgs/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = 'efccc04cb44fc49faddac5876180b369'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-cCAOSG8MBO'			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "/imgs/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "/imgs/favicon.png"
    logoCollapseDark  = "/imgs/favicon.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    # '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：shumlab@foxmail.com <br/>&copy; 2010 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [粤ICP备16023717号](http://beian.miit.gov.cn/)<br/>'
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：geekswg@qq.com <br/>&copy; 2006 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [毕少侠 - geekswg](https://geekswg.js.cool/) | <br/>'
